name: eden_movies_app
description: A lovely movie list app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_sequence_animation: ^4.0.0
  cupertino_icons: ^1.0.2
  dio: ^5.2.1
  go_router: ^8.0.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  retrofit: ^4.0.0
  logger: ^1.4.0
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  retrofit_generator: ^5.0.0

flutter:

  uses-material-design: true
